<?php
class RegistroAutor{
    private $autorId;
    public function getAutorId() {
        return $this->autorId;
    }//end function
    public function setAutorId($autorId) {
        $this->autorId = $autorId;
    }//end function
        
    private $autorNome;
    public function getAutorNome() {
        return $this->autorNome;
    }//end function
    public function setAutorNome($autorNome) {
        $this->autorNome = $autorNome;
    }//end function
    
    private $autorSobrenome;
    public function getAutorSobrenome() {
        return $this->autorSobrenome;
    }//end function
    public function setAutorSobrenome($autorSobrenome) {
        $this->autorSobrenome = $autorSobrenome;
    }//end function
    
    private $autorDataNascimento;
    public function getAutorDataNascimento() {
        return $this->autorDataNascimento;
    }//end function
    public function setAutorDataNascimento($autorDataNascimento) {
        $this->autorDataNascimento = $autorDataNascimento;
    }//end function
    
    private $autorEmail;
    public function getAutorEmail() {
        return $this->autorEmail;
    }//end function
    public function setAutorEmail($autorEmail) {
        $this->autorEmail = $autorEmail;
    }//end function
    
    private $autorEmailGuid;
    public function getAutorEmailGuid() {
        return $this->autorEmailGuid;
    }//end function
    public function setAutorEmailGuid($autorEmailGuid) {
        $this->autorEmailGuid = $autorEmailGuid;
    }//end function
    
    private $autorEmailVerificado;
    public function getAutorEmailVerificado() {
        return $this->autorEmailVerificado;
    }//end function
    public function setAutorEmailVerificado($autorEmailVerificado) {
        $this->autorEmailVerificado = $autorEmailVerificado;
    }//end function
    
    private $autorUsuario;
    public function getAutorUsuario() {
        return $this->autorUsuario;
    }//end function
    public function setAutorUsuario($autorUsuario) {
        $this->autorUsuario = $autorUsuario;
    }//end function
    
    private $autorAssinaturaSenha;
    public function getAutorAssinaturaSenha() {
        return $this->autorAssinaturaSenha;
    }//end function
    public function setAutorAssinaturaSenha($autorAssinaturaSenha) {
        $this->autorAssinaturaSenha = $autorAssinaturaSenha;
    }//end function
    
    private $autorAvisoAddCard;
    public function getAutorAvisoAddCard() {
        return $this->autorAvisoAddCard;
    }//end function
    public function setAutorAvisoAddCard($autorAvisoAddCard) {
        $this->autorAvisoAddCard = $autorAvisoAddCard;
    }//end function
    
    private $autorAvisoMoverCard;
    public function getAutorAvisoMoverCard() {
        return $this->autorAvisoMoverCard;
    }//end function
    public function setAutorAvisoMoverCard($autorAvisoMoverCard) {
        $this->autorAvisoMoverCard = $autorAvisoMoverCard;
    }//end function
    
    private $autorEmailCodigo;
    public function getAutorEmailCodigo() {
        return $this->autorEmailCodigo;
    }//end function
    public function setAutorEmailCodigo($autorEmailCodigo) {
        $this->autorEmailCodigo = $autorEmailCodigo;
    }//end function
    
}//end class

?>








