<?php
class RegistroTutorial{
    private $tutorialID;
    public function getTutorialID(){
        return $this->tutorialID;
    }
    public function setTutorialID($tutorialID){
        $this->tutorialID = $tutorialID;
    }
    
    private $autorID;
    public function getAutorID(){
        return $this->autorID;
    }
    public function setAutorID($autorID){
        $this->autorID = $autorID;
    }
    
    private $tutorialCardNome;
    public function getTutorialCardNome(){
        return $this->tutorialCardNome;
    }
    public function setTutorialCardNome($tutorialCardNome){
        $this->tutorialCardNome = $tutorialCardNome;
    }
    
    private $tutorialCardOrdem;
    public function getTutorialCardOrdem(){
        return $this->tutorialCardOrdem;
    }
    public function setTutorialCardOrdem($tutorialCardOrdem){
        $this->tutorialCardOrdem = $tutorialCardOrdem;
    }
    
    private $tutorialCardTipo;
    public function getTutorialCardTipo(){
        return $this->tutorialCardTipo;
    }
    public function setTutorialCardTipo($tutorialCardTipo) {
        $this->tutorialCardTipo = $tutorialCardTipo;
    }
    
    private $tutorialCardPredefinida;
    public function getTutorialCardPredefinida(){
        return $this->tutorialCardPredefinida;
    }
    public function setTutorialCardPredefinida($tutorialCardPredefinida) {
        $this->tutorialCardPredefinida = $tutorialCardPredefinida;
    }
    
    private $tutorialCardCor;
    public function getTutorialCardCor(){
        return $this->tutorialCardCor;
    }
    public function setTutorialCardCor($tutorialCardCor){
        $this->tutorialCardCor = $tutorialCardCor;
    }
    
    private $tutorialCardPersonalizada;
    public function getTutorialCardPersonalizada(){
        return $this->tutorialCardPersonalizada;
    }
    public function setTutorialCardPersonalizada($tutorialCardPersonalizada){
        $this->tutorialCardPersonalizada = $tutorialCardPersonalizada;
    }
    
    private $tutorialCardTexto;
    public function getTutorialCardTexto(){
        return $this->tutorialCardTexto;
    }
    public function setTutorialCardTexto($tutorialCardTexto){
        $this->tutorialCardTexto = $tutorialCardTexto;
    }
    
    private $tutorialLarguraArvore;
    public function getTutorialLarguraArvore(){
        return $this->tutorialLarguraArvore;
    }
    public function setTutorialLarguraArvore($tutorialLarguraArvore){
        $this->tutorialLarguraArvore = $tutorialLarguraArvore;
    }
    
    private $tutorialLarguraEditor;    
    public function getTutorialLarguraEditor(){
        return $this->tutorialLarguraEditor;
    }        
    public function setTutorialLarguraEditor($tutorialLarguraEditor){
        $this->tutorialLarguraEditor = $tutorialLarguraEditor;
    }
    
    private $tutorialCardPermissao;
    public function getTutorialCardPermissao(){
        return $this->tutorialCardPermissao;
    }
    public function setTutorialCardPermissao($tutorialCardPermissao){
        $this->tutorialCardPermissao = $tutorialCardPermissao;
    }

    private $tutorialCardSenha;
    public function getTutorialCardSenha(){
        return $this->tutorialCardSenha;
    }
    public function setTutorialCardSenha($tutorialCardSenha){
        $this->tutorialCardSenha = $tutorialCardSenha;
    }
    
}//end class
?>


















