        
        <!-- bootstrap - início -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        
        <!-- bootstrap - depencencia jquery -->
        <script src="/js/jquery-bootstrap/jquery.min.js"></script>
        <!-- https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js -->
        
        <!-- bootstrap - depencencia jquery-ui -->
        <link rel="stylesheet" href="/js/jquery-bootstrap/jquery-ui.css">
        <script src="/js/jquery-bootstrap/jquery-ui.min.js"></script>
        
        <!-- bootstrap - depencencia popper -->
        <script src="/js/jquery-bootstrap/popper.min.js"></script>
        <!-- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js -->
        
        <script src="/js/jquery-bootstrap/bootstrap.min.js"></script>
        <!-- https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js -->
        
        <link rel="stylesheet" href="/js/jquery-bootstrap/bootstrap.min.css">
        <!-- https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css -->
        
        <!-- bootstrap - fim -->